# Generated by Django 5.2.6 on 2025-09-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
